<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Modules\Website\app\Models\RestaurantMenuItem;

class RestaurantMenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menuItems = [
            // Appetizers
            [
                'name' => 'Chicken Thai Biriyani',
                'slug' => 'chicken-thai-biriyani',
                'description' => 'Aromatic basmati rice cooked with tender chicken pieces, Thai herbs, and exotic spices',
                'price' => 18.99,
                'discount_price' => null,
                'image' => 'website/images/menu_img_1.jpg',
                'category' => 'Main Course',
                'cuisine_type' => 'Thai',
                'is_vegetarian' => false,
                'is_spicy' => true,
                'spice_level' => 'medium',
                'ingredients' => 'Basmati rice, chicken, lemongrass, Thai basil, chili, ginger, garlic',
                'allergens' => 'None',
                'preparation_time' => 35,
                'calories' => 650,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_popular' => true,
                'order' => 1,
                'status' => true,
            ],
            [
                'name' => 'Beef Masala',
                'slug' => 'beef-masala',
                'description' => 'Tender beef chunks cooked in rich, creamy tomato-based masala sauce with aromatic Indian spices',
                'price' => 22.99,
                'discount_price' => 19.99,
                'image' => 'website/images/menu_img_2.jpg',
                'category' => 'Main Course',
                'cuisine_type' => 'Indian',
                'is_vegetarian' => false,
                'is_spicy' => true,
                'spice_level' => 'hot',
                'ingredients' => 'Beef, tomatoes, cream, onions, ginger, garlic, garam masala, cumin',
                'allergens' => 'Dairy',
                'preparation_time' => 45,
                'calories' => 580,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_popular' => true,
                'order' => 2,
                'status' => true,
            ],
            [
                'name' => 'Dal Makhani',
                'slug' => 'dal-makhani',
                'description' => 'Creamy black lentils slow-cooked with butter, cream, and aromatic spices',
                'price' => 14.99,
                'discount_price' => null,
                'image' => 'website/images/menu_img_3.jpg',
                'category' => 'Main Course',
                'cuisine_type' => 'Indian',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spice_level' => 'mild',
                'ingredients' => 'Black lentils, butter, cream, tomatoes, ginger, garlic, spices',
                'allergens' => 'Dairy',
                'preparation_time' => 40,
                'calories' => 420,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_popular' => true,
                'order' => 3,
                'status' => true,
            ],
            [
                'name' => 'Chicken Chowmein',
                'slug' => 'chicken-chowmein',
                'description' => 'Stir-fried noodles with chicken, vegetables, and savory soy-based sauce',
                'price' => 16.99,
                'discount_price' => null,
                'image' => 'website/images/menu_img_4.jpg',
                'category' => 'Noodles',
                'cuisine_type' => 'Chinese',
                'is_vegetarian' => false,
                'is_spicy' => false,
                'spice_level' => null,
                'ingredients' => 'Egg noodles, chicken, cabbage, carrots, bell peppers, soy sauce',
                'allergens' => 'Gluten, Soy, Eggs',
                'preparation_time' => 20,
                'calories' => 520,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_popular' => true,
                'order' => 4,
                'status' => true,
            ],
            [
                'name' => 'Beef Burger',
                'slug' => 'beef-burger',
                'description' => 'Juicy beef patty with lettuce, tomato, onions, pickles, and special sauce on a toasted bun',
                'price' => 13.99,
                'discount_price' => null,
                'image' => 'website/images/menu_img_5.jpg',
                'category' => 'Burgers',
                'cuisine_type' => 'American',
                'is_vegetarian' => false,
                'is_spicy' => false,
                'spice_level' => null,
                'ingredients' => 'Beef patty, brioche bun, lettuce, tomato, onions, pickles, cheese, sauce',
                'allergens' => 'Gluten, Dairy',
                'preparation_time' => 15,
                'calories' => 680,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_popular' => true,
                'order' => 5,
                'status' => true,
            ],
            [
                'name' => 'Vegetable Spring Rolls',
                'slug' => 'vegetable-spring-rolls',
                'description' => 'Crispy spring rolls filled with fresh vegetables, served with sweet chili sauce',
                'price' => 8.99,
                'discount_price' => null,
                'image' => 'website/images/menu_img_6.jpg',
                'category' => 'Appetizers',
                'cuisine_type' => 'Asian',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spice_level' => null,
                'ingredients' => 'Spring roll wrappers, cabbage, carrots, bean sprouts, mushrooms',
                'allergens' => 'Gluten',
                'preparation_time' => 12,
                'calories' => 280,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => false,
                'is_new' => true,
                'is_popular' => false,
                'order' => 6,
                'status' => true,
            ],
            [
                'name' => 'Margherita Pizza',
                'slug' => 'margherita-pizza',
                'description' => 'Classic Italian pizza with fresh mozzarella, tomato sauce, and basil',
                'price' => 15.99,
                'discount_price' => null,
                'image' => null,
                'category' => 'Pizza',
                'cuisine_type' => 'Italian',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spice_level' => null,
                'ingredients' => 'Pizza dough, tomato sauce, mozzarella, fresh basil, olive oil',
                'allergens' => 'Gluten, Dairy',
                'preparation_time' => 18,
                'calories' => 550,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_popular' => true,
                'order' => 7,
                'status' => true,
            ],
            [
                'name' => 'Pad Thai',
                'slug' => 'pad-thai',
                'description' => 'Traditional Thai stir-fried rice noodles with shrimp, tofu, peanuts, and tamarind sauce',
                'price' => 17.99,
                'discount_price' => 15.99,
                'image' => null,
                'category' => 'Main Course',
                'cuisine_type' => 'Thai',
                'is_vegetarian' => false,
                'is_spicy' => true,
                'spice_level' => 'mild',
                'ingredients' => 'Rice noodles, shrimp, tofu, eggs, bean sprouts, peanuts, tamarind',
                'allergens' => 'Shellfish, Peanuts, Soy, Eggs',
                'preparation_time' => 25,
                'calories' => 610,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => true,
                'is_new' => false,
                'is_popular' => true,
                'order' => 8,
                'status' => true,
            ],
            [
                'name' => 'Caesar Salad',
                'slug' => 'caesar-salad',
                'description' => 'Crisp romaine lettuce with Caesar dressing, croutons, and parmesan cheese',
                'price' => 11.99,
                'discount_price' => null,
                'image' => null,
                'category' => 'Salads',
                'cuisine_type' => 'American',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spice_level' => null,
                'ingredients' => 'Romaine lettuce, Caesar dressing, croutons, parmesan, anchovies',
                'allergens' => 'Dairy, Gluten, Fish',
                'preparation_time' => 8,
                'calories' => 320,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_popular' => false,
                'order' => 9,
                'status' => true,
            ],
            [
                'name' => 'Chocolate Lava Cake',
                'slug' => 'chocolate-lava-cake',
                'description' => 'Warm chocolate cake with a molten chocolate center, served with vanilla ice cream',
                'price' => 9.99,
                'discount_price' => null,
                'image' => null,
                'category' => 'Desserts',
                'cuisine_type' => 'French',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spice_level' => null,
                'ingredients' => 'Dark chocolate, butter, eggs, sugar, flour, vanilla ice cream',
                'allergens' => 'Eggs, Dairy, Gluten',
                'preparation_time' => 15,
                'calories' => 480,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => false,
                'is_new' => true,
                'is_popular' => false,
                'order' => 10,
                'status' => true,
            ],
            [
                'name' => 'Tom Yum Soup',
                'slug' => 'tom-yum-soup',
                'description' => 'Spicy and sour Thai soup with shrimp, mushrooms, lemongrass, and lime',
                'price' => 12.99,
                'discount_price' => null,
                'image' => null,
                'category' => 'Soups',
                'cuisine_type' => 'Thai',
                'is_vegetarian' => false,
                'is_spicy' => true,
                'spice_level' => 'hot',
                'ingredients' => 'Shrimp, mushrooms, lemongrass, galangal, lime, chili, fish sauce',
                'allergens' => 'Shellfish, Fish',
                'preparation_time' => 20,
                'calories' => 180,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => false,
                'is_new' => false,
                'is_popular' => true,
                'order' => 11,
                'status' => true,
            ],
            [
                'name' => 'Veggie Delight Pizza',
                'slug' => 'veggie-delight-pizza',
                'description' => 'Loaded with fresh vegetables, olives, and mozzarella cheese',
                'price' => 16.99,
                'discount_price' => 14.99,
                'image' => null,
                'category' => 'Pizza',
                'cuisine_type' => 'Italian',
                'is_vegetarian' => true,
                'is_spicy' => false,
                'spice_level' => null,
                'ingredients' => 'Pizza dough, bell peppers, onions, mushrooms, olives, tomatoes, mozzarella',
                'allergens' => 'Gluten, Dairy',
                'preparation_time' => 18,
                'calories' => 520,
                'available_in_pos' => true,
                'available_in_website' => true,
                'is_featured' => false,
                'is_new' => true,
                'is_popular' => false,
                'order' => 12,
                'status' => true,
            ],
        ];

        foreach ($menuItems as $item) {
            RestaurantMenuItem::create($item);
        }
    }
}
